// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  edition: defineAsyncComponent(() => import("./Edition/index.vue")),
  elsewhere_slice: defineAsyncComponent(
    () => import("./ElsewhereSlice/index.vue")
  ),
  exhibition_slice: defineAsyncComponent(
    () => import("./ExhibitionSlice/index.vue")
  ),
  test_section: defineAsyncComponent(() => import("./TestSection/index.vue")),
});
